// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.dataAccess.Concrete;

namespace backend.dataAccess.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("backend.entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("addedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("birthDate")
                        .HasColumnType("text");

                    b.Property<string>("birthPlace")
                        .HasColumnType("text");

                    b.Property<int?>("chiefUserId")
                        .HasColumnType("int");

                    b.Property<string>("company")
                        .HasColumnType("text");

                    b.Property<string>("degree")
                        .HasColumnType("text");

                    b.Property<string>("identyNum")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("updatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("chiefUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.entity.User", b =>
                {
                    b.HasOne("backend.entity.User", "chiefUser")
                        .WithMany()
                        .HasForeignKey("chiefUserId");

                    b.Navigation("chiefUser");
                });
#pragma warning restore 612, 618
        }
    }
}
